defmodule Cultulator.Html do
  use Eml
  require Logger

  def layout(do: contents) do
    body do
      common_header()
      contents
      common_footer()
    end
  end

  defp common_header do
    # nothing here
  end

  defp common_footer do
    footer do
      [
        "Generated by ",
        a([href: "https://github.com/#{github_project()}"], "cultulator"),
        " #{version()}"
      ]
    end
  end

  defp github_project do
    case System.cmd("git", ~w{remote get-url origin}) do
      {"git@github.com:" <> path, 0} ->
        path
        |> String.trim()
        |> Path.rootname(".git")

      {"https://github.com/" <> path, 0} ->
        path
        |> String.trim()
        |> Path.rootname(".git")

      _ ->
        Logger.warn("Can't determine Github URL")
        "wisq/cultulator"
    end
  end

  defp version do
    mv = Mix.Project.config() |> Keyword.fetch!(:version)
    gv = git_version()

    "v#{mv} [#{gv}]"
  end

  defp git_version do
    case System.cmd("git", ~w{rev-parse HEAD}) do
      {rev, 0} ->
        rev
        |> String.trim()
        |> String.slice(0..6)

      _ ->
        Logger.warn("Can't determine git version")
        "unknown"
    end
  end
end
