language: elixir
sudo: false
elixir:
  - 1.7
otp_release:
  - 21.2
env:
  - MIX_ENV=test
cache:
  directories:
    - _build/test/lib
    - deps
before_cache:
  - rm -rf _build/test/lib/cultulator
notifications:
  email: false
  slack:
    on_success: change
    rooms:
      - secure: Wftn34N8fyrD/WbzOyHSPtnek2d61+iEn5wCVPEwa3DvR3kFt3jwgtlysUIzmSnWNYyt27ylOSxmCa4j8y3xICNj92XtiOfFadoRVONG+k9W7IKG2hRO+1KIKVJjBhhIHgEdkfPJkV83LzMaUIUzok03GwzSfi2tIn02aBZVYfLa9sENsjhv3uaFtgpi1QmmZOu2fxXEsAYC4M69xL9vyAhIXmYVXlo1U+um6c8g40Z1JJfxLWuAEO/ZHk5xl9kmeo9VabuoES4N8CRLBX96oeAH8FHG3WCwqvoxD9VKlNMhXE0G0l0QDukZrx3RR2KueZYeuwtJajCGOBZylybfXuto8qSnyrgpBaf1M37K+HXnZCk/ghIsQy/teXdCdUBUm2ViIBzHB+lvN5oaXLx+mYYnOcU6aSakcs9WZSO/MdsyEbvK5lbAJK11K+Ed5OyzhPmybNkZCVGFUjnEcEvwXX+B4uuXKeYzYn0bvQ+ZPgsFj5FhcCBN3z3Hjorb1pPwxRNo+fIQXHw58idFtSicf7B9Z3putodAKrB+rHUEDIEFQw1VSLlPopsiofcVv6u6gVijkIvdPoRTPEydQuknEVD7zY+Vy9zaWXVgcv9OQsH4/V0RIoIL7VFLu4Er1Xj7gNdG6pQV60KPt77+QmYZPfGiJImhrl7C20CaGdSwQC8=
before_deploy: "mix cult.expeditions"
deploy:
  provider: s3
  access_key_id: AKIAJX73U5SBXBWI4HDA
  secret_access_key:
    secure: f60wYuU50tEY5XpcVhaRjLQ3Do2QUM74UHdISeh//SSPGKat5HHKLA2nGyRH6Kts5J6NMMxqlNqlh38EaN5LWKIwRBAGaIArAm80tPpm4bHzTO8ykxUAjbQhQCQQHzYg9raLzcOhxZgbjael8KK5mOMDOhPRfMSGvUTum/bGme3kWZfbTN/86aFp0s0D1A2Jvqs+tBO0Jj8QSRXou6yqtIViYdbtfFZvUZ5FgFiHHIHG/+U/+Z4S0AB/xP0x2zbxTaMjQcK0WLahbnS/VgC9wZEf0BBI75xQYfjQHcshZK8d/2Pn0ik05p5mY4BMFzpmAO/htrkbQiAguXXkISIQRbmhmXLz4hFoxel6ak5Nd3v+H7sNxd5Ebjvl14AFGg+ihty1RdLd4pv965vmrrH69r4wWL9xdJZyIncv4KfTmEdx+NHApNOcQHMKOOkPtV9qojBEiVUsiWzps6BTjQbkWEC8mt+UaTooyEWpM+wTcY2TwdHTQ3yCxcIWbtB6A53BcnFru6rYgy/hBYzQ2IMbYZFDVYMhEA1v93gqgf96h5PbSNmykrWkdC7VGmcBXfeKd2bM+SVn837KkJ0AqkpKyPbjpHTDuFel2KAf4d2xxP6qYkGgPNBIY6hd2avE6h9l3RWxdPe2aCwLdEBzeG1kjWEQ5d/LWNActTW+pktZ1cE=
  bucket: cult.wisq.net
  local-dir: _build/dev/pages
  acl: public_read
  on:
    repo: wisq/cultulator
